const REFRESH_SUGGESTIONS = 'REFRESH_SUGGESTIONS'
const REFRESH_NOTIFICATION_COUNTER = 'REFRESH_NOTIFICATION_COUNTER'
const REFRESH_PROFILE = 'REFRESH_PROFILE'

export default {
    REFRESH_SUGGESTIONS,
    REFRESH_NOTIFICATION_COUNTER,
    REFRESH_PROFILE
}